- name: Set Master parameters

  hosts: "{{ master }}"
  tasks:
  - name: Init and mount Data disks
    script: datadisk-1.sh

  - name: Reboot hosts
    reboot:

- name: Set Segments parameters

  hosts: "{{ segments }}"
  tasks:
  - name: Init and mount Data disks
    script: datadisk-2.sh

  - name: Reboot hosts
    reboot:

