- name: Set monitoring

  hosts: "{{ hosts }}"
  tasks:
  - name: Set 5s metrics interval in Diamond
    shell: sed -i 's/interval = 60/interval = 5/' /etc/diamond/diamond.conf

  - name: Get all the CPU metrics from hosts (simple=false)
    shell: sed -i 's/simple = True/simple = False/' /etc/diamond/collectors/CPUCollector.conf
    
  - name: Copy patch
    copy: 
      src: cpu.py.patch
      dest: /tmp/cpu.py.patch

  - name: Patch diamond
    shell: patch -d/ -p0 </tmp/cpu.py.patch
  
  - name: Restart diamond
    service:
      name: diamond
      state: restarted
