- name: Set parameters

  hosts: "{{ hosts }}"
  tasks:
  - name: Update all packages
    yum: name=* state=latest update_cache=true

  - name: Install the latest tree package
    yum: name=tree state=latest update_cache=true

  - name: Set MTU permanently
    shell: echo MTU=\"8888\" >> /etc/sysconfig/network-scripts/ifcfg-eth0

  - name: Set MTU in Runtime
    shell: ip link set mtu 8888 dev eth0

  - name: Install SberCloud monitoring agent
    shell: cd /usr/local && wget https://telescope-ru-moscow-1.obs.ru-moscow-1.hc.sbercloud.ru/scripts/agentInstall.sh && chmod 755 agentInstall.sh && ./agentInstall.sh

  - name: Set Kernel parameters
    script: kernel.sh
  
  - name: Reboot hosts
    reboot:
